### ISSUE TITLE
Unable to launch packaging process from Gradle

### ISSUE THREAD

**Issue by petervelosy** [freeplane/gradle-plugin#1]
When executing ./gradlew packageAddon using Gradle Wrapper 6.7.1, Freeplane 1.9.11 and Developer Tools 0.9.26, prepareAddonSource completes successfully but the packaging process fails with 
"WARNING: addons.devtools.releaseAddOn_on_single_node is not a valid menu item key.".

This was encountered when packaging the addon from the master branch of https://github.com/petervelosy/freeplane-zotero under Arch Linux. The environment variable FREEPLANE_DIR was set to /usr/share/freeplane

On the same system, with the same user, executing "freeplane -S -Xaddons.devtools.releaseAddOn_on_single_node" from a terminal launches the packaging function of Developer Tools correctly.

**Comment by dpolivaev** [comment]
I guess you could try to specify userDirectory in the configuration options because otherwise Developer Tools add-on can not be found. Could you please try it and write back if it helps?

**Comment by petervelosy** [comment]
I've tried setting userDirectory in the config options but it unfortunately still results in the same error.

**Comment by petervelosy** [comment]
Ah, found the problem, userDirectory should be specified without the version number suffix. 

I would suggest updating the README with this information, as it turns out userDirectory is not optional (as currently indicated by the README) but compulsory for packageAddon to work correctly.

**Comment by dpolivaev** [comment]
Thanks, I added this information to the readme
