### ISSUE TITLE
Bug: Gradle plugin does not build java 8 compatible libraries by default

### ISSUE THREAD

**Issue by HaaiHenkie** [freeplane/gradle-plugin#3]
## Describe the bug
As a add-on developer I would like to be able to build an add-on with a library that will work for all Java versions that Freeplane supports. That means the library should be compatible with Java 8, the earliest version Freeplane supports. When I run the Gradle plugin under JDK 8 it does exactly as expected. If I run the Gradle plugin under a newer JDK I would expect the same, i.e. (a) it will compile a java 8 compatible version and (b) if the source refers to a library added to version newer than java 8 it wil not compile. However the Gradle plugin does not do this by default.

## To Reproduce

To reproduce you need to carry out 2 scenarios, each with a different expected result. The 2 scenarios are held against 3 possible solutions.

### Scenarios and expected results
**Remark:** in following terminal commands the preceding `./` should be left out on windows.

**Starting situation for all scenarios:** Gradle wrapper **6.9.1** runs under JDK 11, i.e. `./gradlew -v` run from one of the scenario directories shows that Gradle is running under a JVM version 11. The environment variable FREEPLANE_DIR points to the installation directory of Freeplane.

#### Scenario 1: successful compilation
**Starting situation:** the example add-on project from the Freeplane Gradle plugin repository in the following zip
[Scenario 1 - successful compilation.zip](https://github.com/freeplane/gradle-plugin/files/8975213/Scenario.1.-.successful.compilation.zip). It is unzipped to directory "Scenario 1 - successful compilation"

Steps:

1. In a terminal change to project directory "Scenario 1 - successful compilation"
2. Run `./gradlew packagAddon`
3. Confirm the dialogues in the Freeplane instance packaging the add-on
4. Check the output of the command under step 2
5. Run `javap -verbose build/classes/groovy/main/greetings/GroovyGreetings.class | grep "major"` Under Windows use `findstr` instead of `grep`.

Expected result: the build is successful and the result of step 5 is `major version: 52` which corresponds with Java 8.

#### Scenario 2: incompatible library
**Starting situation:** the example add-on project from the Freeplane Gradle plugin repository with `HttpClientSynchronous.groovy` added to `src/main/groovy/greetings/`. This groovy class imports `java.net.http.HttpClient` that is part of Java 11 and not of Java 8. The add-on project files in [Scenario 2 - incompatible library.zip](https://github.com/freeplane/gradle-plugin/files/8975227/Scenario.2.-.incompatible.library.zip) are unzipped to directory "Scenario 2 - incompatible library"

Steps:

1. In a terminal change to project directory "Scenario 2 - incompatible library"
2. Run `./gradlew packagAddon`
3. If necessary, confirm the dialogues in the Freeplane instance packaging the add-on
4. Check the output of the command under step 2

Expected result: the build fails because the HttpClient library cannot be resolved in Java 8.

#### Solution 1: default behaviour
**Assumption:** The `build.gradle` file of the plugin contains

```gradle
targetCompatibility='1.8'
sourceCompatibility='1.8'
```

which takes care of Java 8 compatibility of the compiled library

**Result scenario 1:** :x: `major version: 55` which corresponds with Java 11

**Result scenario 2:** :x: library compiles successfully

#### Solution 2: add Java version 8 compatibility options to build.gradle of add-on project
**Assumption:** Putting the Java version 8 compatibility options

```gradle
targetCompatibility='1.8'
sourceCompatibility='1.8'
```

in the `build.gradle` file of the add-on project takes care of Java 8 compatibility of the compiled library

**Starting situation for both scenarios:** above lines are uncommented in the `build.gradle` file of the add-on project.

**Result scenario 1:** :white_check_mark: `major version: 52` which corresponds with Java 8

**Result scenario 2:** :x: library compiles successfully

#### Solution 3: define Java 8 toolchain to build.gradle of add-on project
**Assumption:** Defining the Java 8 toolchain

```gradle
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
```

in the `build.gradle` file of the add-on project takes care of Java 8 compatibility of the compiled library

**Starting situation for both scenarios:** above lines are uncommented in the `build.gradle` file of the add-on project and scenario 2 lines are commented.

**Result scenario 1:** :white_check_mark: `major version: 52` which corresponds with Java 8

**Result scenario 2:** :white_check_mark: compile fails because library `java.net.http.HttpClient` cannot be resolved

## Conclusion

Please define Java 8 toolchain in the example project `build.gradle` in the `README.md` of the repository.
Please upgrade the gradle wrapper for the example project to 6.9.1. Solution 3 will not work with Gradle 6.7.1, maybe a bug since Java chaintools were introduced in Gradle 6.7. Gradle plugin still works fine with Gradle 6.9.1, but not with 7.0 and higher.

## Java toolchains in Gradle
When you specify the version of the Java toolchain, Gradle will use a locally installed JDK or JRE with that version. If no matching JDK or JRE is available, Gradle will automatically download one and use that. Statement in scenario 3 defines the toolchain globally, i.e. for all Java tasks en for the Groovy compile task. It is also possible to define the toolchain for specific task types.

To check if Gradle detects your locally installed JDKs, run the following command from your Gradle project directory.

`./gradlew -q javaToolchains`

In my case the Adoptium JDKs under Windows were not detected, except the active one. For Gradle to detect them, they need to be registered in the Windows registry. This is an option when you use the \*.msi download to install an Adoptium JDK.

For further information see: https://docs.gradle.org/current/userguide/toolchains.html

**Comment by HaaiHenkie** [comment]
Hello Dimitry,

I see you opted for solution 2.  Why not for solution 3? It is better in my opinion because it checks if you accidentally did not include a library added to a later JVM version which cannot be resolved under Java 8. 

Cheers,

Henk

**Comment by dpolivaev** [comment]
Expect from me neither best nor conscious decisions. I don't use this thing at all. Give me a pull request and explain your reasons, I would be happy to accept it.

**Comment by HaaiHenkie** [comment]
I have submitted a pull request
